INC_DIR=./inc
OBJ_DIR=./obj
LIB_DIR=./lib
SRC_DIR=./src
BIN_DIR=./bin

CC=gcc
RM=rm -f

SOURCES:=${shell find $(SRC_DIR) -name '*.c'}
OBJECTS:=$(patsubst $(SRC_DIR)%.c,$(OBJ_DIR)%.o,${SOURCES})
TARGET:=${BIN_DIR}/libcutlery.a

CFLAGS=-I${INC_DIR}

${OBJ_DIR}/%.o : ${SRC_DIR}/%.c ${INC_DIR}/%.h
	${CC} ${CFLAGS} -c $< -o $@

$(TARGET) : ${OBJECTS}
	ar rcs $@ ${OBJECTS}

all : ${BIN_DIR}/$(TARGET)

clean :
	$(RM) $(BIN_DIR)/* $(OBJ_DIR)/*

path : 
	@echo "export CUTLERY_PATH=\`pwd\`"
